// monorepo/turborepo/react-vite/apps/account/src/App.tsx
import { useState } from 'react';
import { Routes, Route } from 'react-router';
import { AccountList } from './pages/AccountList';
import { CreateAccount } from './pages/CreateAccount';

export default function App() {
  const [accounts, setAccounts] = useState([
    { id: 1, name: 'German Sanchez', email: 'german.sanchez@example.com', status: 'active' },
    { id: 2, name: 'Jane Smith', email: 'jane@acme.inc', status: 'pending' },
    { id: 3, name: 'Robert Fox', email: 'robert@design.co', status: 'active' },
  ]);

  const handleCreate = (newAccount: any) => {
    setAccounts([...accounts, newAccount]);
  };

  const handleDelete = (id: number) => {
    setAccounts(accounts.filter(a => a.id !== id));
  };

  return (
    <Routes>
      <Route index element={<AccountList accounts={accounts} onDelete={handleDelete} />} />
      <Route path="new" element={<CreateAccount onCreate={handleCreate} />} />
    </Routes>
  );
}

// monorepo/turborepo/angular/apps/account/src/app/app.component.ts
import { Component, signal, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet],
  template: `<router-outlet></router-outlet>`
})
export class AppComponent {
  accounts = signal([
    { id: 1, name: 'German Sanchez', email: 'german.sanchez@example.com', status: 'active' },
    { id: 2, name: 'Jane Smith', email: 'jane@acme.inc', status: 'pending' },
    { id: 3, name: 'Robert Fox', email: 'robert@design.co', status: 'active' },
  ]);

  handleCreate(newAccount: any) {
    this.accounts.update(prev => [...prev, newAccount]);
  }

  handleDelete(id: number) {
    this.accounts.update(prev => prev.filter(a => a.id !== id));
  }
}
